import type {
  Flag,
  Environment,
  Experiment,
  ExperimentResults,
  AuditEntry,
  User,
  Project,
} from "./types";

// ── Environments ──────────────────────────────────────────────────
export const mockEnvironments: Environment[] = [
  {
    id: "env-1",
    key: "development",
    name: "Development",
    color: "#3b82f6",
    description: "Local development environment",
    production: false,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
    projectId: "proj-1",
    order: 0,
  },
  {
    id: "env-2",
    key: "staging",
    name: "Staging",
    color: "#eab308",
    description: "Pre-production testing",
    production: false,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
    projectId: "proj-1",
    order: 1,
  },
  {
    id: "env-3",
    key: "production",
    name: "Production",
    color: "#ef4444",
    description: "Live production environment",
    production: true,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
    projectId: "proj-1",
    order: 2,
  },
];

// ── Flags ─────────────────────────────────────────────────────────
export const mockFlags: Flag[] = [
  {
    id: "flag-1",
    key: "dark-mode",
    name: "Dark Mode",
    description: "Enable dark mode across the application",
    type: "boolean",
    tags: ["ui", "frontend"],
    variations: [
      { key: "on", value: true, name: "Enabled" },
      { key: "off", value: false, name: "Disabled" },
    ],
    defaultVariation: "off",
    environments: {
      "env-1": {
        environmentId: "env-1",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-20T10:00:00Z",
      },
      "env-2": {
        environmentId: "env-2",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-18T10:00:00Z",
      },
      "env-3": {
        environmentId: "env-3",
        enabled: true,
        rolloutPercentage: 75,
        targetingRules: [
          {
            id: "rule-1",
            description: "Beta users",
            clauses: [
              { attribute: "userGroup", operator: "in", values: ["beta", "internal"] },
            ],
            variation: "on",
            rolloutPercentage: 100,
            priority: 0,
          },
        ],
        killSwitchActive: false,
        lastModified: "2025-04-22T14:30:00Z",
      },
    },
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-04-22T14:30:00Z",
    createdBy: "user-1",
    archived: false,
    projectId: "proj-1",
  },
  {
    id: "flag-2",
    key: "new-checkout-flow",
    name: "New Checkout Flow",
    description: "Redesigned checkout experience with fewer steps",
    type: "boolean",
    tags: ["checkout", "experiment"],
    variations: [
      { key: "on", value: true, name: "New Flow" },
      { key: "off", value: false, name: "Legacy Flow" },
    ],
    defaultVariation: "off",
    environments: {
      "env-1": {
        environmentId: "env-1",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-10T10:00:00Z",
      },
      "env-2": {
        environmentId: "env-2",
        enabled: true,
        rolloutPercentage: 50,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-12T10:00:00Z",
      },
      "env-3": {
        environmentId: "env-3",
        enabled: false,
        rolloutPercentage: 0,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-05T10:00:00Z",
      },
    },
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-04-12T10:00:00Z",
    createdBy: "user-1",
    archived: false,
    projectId: "proj-1",
  },
  {
    id: "flag-3",
    key: "ai-recommendations",
    name: "AI Recommendations",
    description: "ML-powered product recommendations engine",
    type: "string",
    tags: ["ml", "backend", "performance"],
    variations: [
      { key: "v1", value: "collaborative-filtering", name: "Collaborative Filtering" },
      { key: "v2", value: "neural-network", name: "Neural Network" },
      { key: "off", value: "none", name: "Disabled" },
    ],
    defaultVariation: "off",
    environments: {
      "env-1": {
        environmentId: "env-1",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-15T10:00:00Z",
      },
      "env-2": {
        environmentId: "env-2",
        enabled: true,
        rolloutPercentage: 30,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-16T10:00:00Z",
      },
      "env-3": {
        environmentId: "env-3",
        enabled: false,
        rolloutPercentage: 0,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-01T10:00:00Z",
      },
    },
    createdAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-04-16T10:00:00Z",
    createdBy: "user-2",
    archived: false,
    projectId: "proj-1",
  },
  {
    id: "flag-4",
    key: "rate-limiter-v2",
    name: "Rate Limiter V2",
    description: "Token bucket rate limiter with sliding window",
    type: "json",
    tags: ["backend", "infrastructure"],
    variations: [
      { key: "default", value: { maxRequests: 100, windowMs: 60000 }, name: "Default" },
      { key: "strict", value: { maxRequests: 50, windowMs: 60000 }, name: "Strict" },
    ],
    defaultVariation: "default",
    environments: {
      "env-1": {
        environmentId: "env-1",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-20T10:00:00Z",
      },
      "env-2": {
        environmentId: "env-2",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-20T10:00:00Z",
      },
      "env-3": {
        environmentId: "env-3",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-20T10:00:00Z",
      },
    },
    createdAt: "2025-04-01T10:00:00Z",
    updatedAt: "2025-04-20T10:00:00Z",
    createdBy: "user-1",
    archived: false,
    projectId: "proj-1",
  },
  {
    id: "flag-5",
    key: "search-v3",
    name: "Search V3",
    description: "Elasticsearch-backed full-text search with typo tolerance",
    type: "boolean",
    tags: ["search", "backend"],
    variations: [
      { key: "on", value: true, name: "Enabled" },
      { key: "off", value: false, name: "Disabled" },
    ],
    defaultVariation: "off",
    environments: {
      "env-1": {
        environmentId: "env-1",
        enabled: true,
        rolloutPercentage: 100,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-25T10:00:00Z",
      },
      "env-2": {
        environmentId: "env-2",
        enabled: false,
        rolloutPercentage: 0,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-22T10:00:00Z",
      },
      "env-3": {
        environmentId: "env-3",
        enabled: false,
        rolloutPercentage: 0,
        targetingRules: [],
        killSwitchActive: false,
        lastModified: "2025-04-20T10:00:00Z",
      },
    },
    createdAt: "2025-04-10T10:00:00Z",
    updatedAt: "2025-04-25T10:00:00Z",
    createdBy: "user-2",
    archived: false,
    projectId: "proj-1",
  },
];

// ── Experiments ───────────────────────────────────────────────────
export const mockExperiments: Experiment[] = [
  {
    id: "exp-1",
    key: "checkout-flow-test",
    name: "Checkout Flow A/B Test",
    description: "Testing the new streamlined checkout against the legacy flow",
    flagId: "flag-2",
    flagKey: "new-checkout-flow",
    status: "running",
    variations: [
      { key: "control", name: "Legacy Flow", weight: 50, isControl: true },
      { key: "treatment", name: "New Flow", weight: 50, isControl: false },
    ],
    trafficPercentage: 100,
    startDate: "2025-04-01T00:00:00Z",
    targetMetric: "checkout_completion",
    guardrailMetrics: [
      { key: "error_rate", name: "Error Rate", type: "conversion", minimumDetectableEffect: 0.5 },
      { key: "page_load_time", name: "Page Load Time", type: "count", minimumDetectableEffect: 100 },
    ],
    createdAt: "2025-03-28T10:00:00Z",
    updatedAt: "2025-04-20T10:00:00Z",
    projectId: "proj-1",
  },
  {
    id: "exp-2",
    key: "recommendation-engine",
    name: "ML Recommendation Engine",
    description: "Comparing collaborative filtering vs neural network recommendations",
    flagId: "flag-3",
    flagKey: "ai-recommendations",
    status: "complete",
    variations: [
      { key: "control", name: "Collaborative Filtering", weight: 50, isControl: true },
      { key: "treatment", name: "Neural Network", weight: 50, isControl: false },
    ],
    trafficPercentage: 80,
    startDate: "2025-02-15T00:00:00Z",
    endDate: "2025-03-15T00:00:00Z",
    targetMetric: "click_through_rate",
    guardrailMetrics: [
      { key: "latency_p99", name: "P99 Latency", type: "count", minimumDetectableEffect: 50 },
    ],
    createdAt: "2025-02-10T10:00:00Z",
    updatedAt: "2025-03-15T10:00:00Z",
    projectId: "proj-1",
  },
  {
    id: "exp-3",
    key: "search-ranking",
    name: "Search Ranking Algorithm",
    description: "Testing BM25 vs vector similarity scoring",
    flagId: "flag-5",
    flagKey: "search-v3",
    status: "draft",
    variations: [
      { key: "control", name: "BM25", weight: 50, isControl: true },
      { key: "treatment", name: "Vector Similarity", weight: 50, isControl: false },
    ],
    trafficPercentage: 50,
    targetMetric: "search_success_rate",
    guardrailMetrics: [],
    createdAt: "2025-04-20T10:00:00Z",
    updatedAt: "2025-04-20T10:00:00Z",
    projectId: "proj-1",
  },
  {
    id: "exp-4",
    key: "rate-limit-threshold",
    name: "Rate Limit Threshold Test",
    description: "Finding optimal rate limiting threshold for API endpoints",
    flagId: "flag-4",
    flagKey: "rate-limiter-v2",
    status: "paused",
    variations: [
      { key: "control", name: "100 req/min", weight: 50, isControl: true },
      { key: "treatment", name: "50 req/min", weight: 50, isControl: false },
    ],
    trafficPercentage: 25,
    startDate: "2025-04-10T00:00:00Z",
    targetMetric: "api_error_rate",
    guardrailMetrics: [],
    createdAt: "2025-04-08T10:00:00Z",
    updatedAt: "2025-04-15T10:00:00Z",
    projectId: "proj-1",
  },
];

export const mockExperimentResults: ExperimentResults = {
  experimentId: "exp-2",
  status: "complete",
  totalSampleSize: 48250,
  startDate: "2025-02-15T00:00:00Z",
  endDate: "2025-03-15T00:00:00Z",
  variationResults: [
    {
      variationKey: "control",
      name: "Collaborative Filtering",
      isControl: true,
      sampleSize: 24100,
      conversions: 3132,
      conversionRate: 12.99,
      improvementOverControl: 0,
      probabilityToBeatControl: 0,
      credibleInterval: { lower: 12.55, upper: 13.43 },
      isWinner: false,
      isStatisticallySignificant: false,
    },
    {
      variationKey: "treatment",
      name: "Neural Network",
      isControl: false,
      sampleSize: 24150,
      conversions: 3864,
      conversionRate: 16.0,
      improvementOverControl: 23.17,
      probabilityToBeatControl: 99.7,
      credibleInterval: { lower: 15.53, upper: 16.47 },
      isWinner: true,
      isStatisticallySignificant: true,
    },
  ],
  guardrailResults: [
    {
      metricKey: "latency_p99",
      metricName: "P99 Latency",
      passed: true,
      controlValue: 145,
      treatmentValue: 152,
      pValue: 0.32,
      message: "No significant increase in P99 latency",
    },
  ],
  recommendation: {
    action: "ship",
    confidence: 0.97,
    reasoning:
      "The neural network model shows a statistically significant 23.17% improvement in click-through rate with no degradation in P99 latency. The credible intervals are well-separated.",
    suggestedNextSteps: [
      "Roll out neural network model to 100% of production traffic",
      "Monitor latency metrics for 48 hours post-rollout",
      "Archive collaborative filtering model after validation period",
    ],
  },
  lastUpdated: "2025-03-15T10:00:00Z",
};

// ── Audit Entries ─────────────────────────────────────────────────
export const mockAuditEntries: AuditEntry[] = [
  {
    id: "audit-1",
    action: "flag.toggled",
    actor: "Sarah Chen",
    actorEmail: "sarah@rollout.dev",
    targetType: "flag",
    targetId: "flag-1",
    targetName: "Dark Mode",
    timestamp: "2025-05-07T14:30:00Z",
    changes: { enabled: { before: false, after: true } },
    metadata: { environment: "production" },
    projectId: "proj-1",
    environmentId: "env-3",
  },
  {
    id: "audit-2",
    action: "rollout.updated",
    actor: "Marcus Johnson",
    actorEmail: "marcus@rollout.dev",
    targetType: "flag",
    targetId: "flag-1",
    targetName: "Dark Mode",
    timestamp: "2025-05-07T13:15:00Z",
    changes: { rolloutPercentage: { before: 50, after: 75 } },
    metadata: { environment: "production" },
    projectId: "proj-1",
    environmentId: "env-3",
  },
  {
    id: "audit-3",
    action: "experiment.started",
    actor: "Sarah Chen",
    actorEmail: "sarah@rollout.dev",
    targetType: "experiment",
    targetId: "exp-1",
    targetName: "Checkout Flow A/B Test",
    timestamp: "2025-05-07T10:00:00Z",
    projectId: "proj-1",
  },
  {
    id: "audit-4",
    action: "flag.created",
    actor: "Alex Rivera",
    actorEmail: "alex@rollout.dev",
    targetType: "flag",
    targetId: "flag-5",
    targetName: "Search V3",
    timestamp: "2025-05-06T16:45:00Z",
    projectId: "proj-1",
  },
  {
    id: "audit-5",
    action: "targeting.updated",
    actor: "Marcus Johnson",
    actorEmail: "marcus@rollout.dev",
    targetType: "flag",
    targetId: "flag-1",
    targetName: "Dark Mode",
    timestamp: "2025-05-06T11:20:00Z",
    changes: { rules: { before: 0, after: 1 } },
    metadata: { environment: "production", ruleDescription: "Beta users" },
    projectId: "proj-1",
    environmentId: "env-3",
  },
  {
    id: "audit-6",
    action: "environment.created",
    actor: "Sarah Chen",
    actorEmail: "sarah@rollout.dev",
    targetType: "environment",
    targetId: "env-3",
    targetName: "Production",
    timestamp: "2025-05-05T09:00:00Z",
    projectId: "proj-1",
  },
  {
    id: "audit-7",
    action: "experiment.completed",
    actor: "System",
    actorEmail: "system@rollout.dev",
    targetType: "experiment",
    targetId: "exp-2",
    targetName: "ML Recommendation Engine",
    timestamp: "2025-05-04T23:59:00Z",
    metadata: { winner: "Neural Network", improvement: "23.17%" },
    projectId: "proj-1",
  },
  {
    id: "audit-8",
    action: "flag.killed",
    actor: "Sarah Chen",
    actorEmail: "sarah@rollout.dev",
    targetType: "flag",
    targetId: "flag-2",
    targetName: "New Checkout Flow",
    timestamp: "2025-05-04T15:30:00Z",
    metadata: { environment: "production", reason: "High error rate detected" },
    projectId: "proj-1",
    environmentId: "env-3",
  },
  {
    id: "audit-9",
    action: "user.invited",
    actor: "Sarah Chen",
    actorEmail: "sarah@rollout.dev",
    targetType: "user",
    targetId: "user-3",
    targetName: "Alex Rivera",
    timestamp: "2025-05-03T10:00:00Z",
    metadata: { role: "editor" },
    projectId: "proj-1",
  },
  {
    id: "audit-10",
    action: "project.updated",
    actor: "Marcus Johnson",
    actorEmail: "marcus@rollout.dev",
    targetType: "project",
    targetId: "proj-1",
    targetName: "Rollout Core",
    timestamp: "2025-05-02T14:00:00Z",
    changes: { name: { before: "Core Platform", after: "Rollout Core" } },
    projectId: "proj-1",
  },
];

// ── Users ─────────────────────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "sarah@rollout.dev",
    name: "Sarah Chen",
    role: "owner",
    avatarUrl: undefined,
    lastLogin: "2025-05-07T14:30:00Z",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "user-2",
    email: "marcus@rollout.dev",
    name: "Marcus Johnson",
    role: "admin",
    avatarUrl: undefined,
    lastLogin: "2025-05-07T13:15:00Z",
    createdAt: "2025-01-05T00:00:00Z",
  },
  {
    id: "user-3",
    email: "alex@rollout.dev",
    name: "Alex Rivera",
    role: "editor",
    avatarUrl: undefined,
    lastLogin: "2025-05-06T16:45:00Z",
    createdAt: "2025-03-10T00:00:00Z",
  },
];

// ── Project ───────────────────────────────────────────────────────
export const mockProject: Project = {
  id: "proj-1",
  key: "rollout-core",
  name: "Rollout Core",
  description: "Core feature flag platform",
  apiKey: "pk_live_r0ll0ut_a8f3k2m9x1p7",
  serverApiKey: "sk_live_r0ll0ut_z9y8x7w6v5u4",
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-05-02T14:00:00Z",
};
